config/routes.rb
Rails.application.routes.draw do
  # get 'movies/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :movies do
    collection do
      get 'search'
    end
  end
  # Defines the root path route ("/")
  root "movies#index"
end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Actor < ApplicationRecord
  include SearchCop

  search_scope :search do
    attributes :first_name, :last_name
  end
  
  has_many :movie_actors
  has_many :movies, through: :movie_actors

  def name
    first_name+" "+last_name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Country < ApplicationRecord
  has_many :movie_countries
  has_many :movies, through: :movie_countries
end

app/models/director.rb
# == Schema Information
#
# Table name: directors
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Director < ApplicationRecord
  has_many :movie_directors
  has_many :movies, through: :movie_directors

  def name
    first_name+" "+last_name
  end
end

app/models/filming_location.rb
# == Schema Information
#
# Table name: filming_locations
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class FilmingLocation < ApplicationRecord
  has_many :movie_filming_locations
  has_many :movies, through: :movie_filming_locations
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  year        :string
#  rating      :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Movie < ApplicationRecord
  has_many :movie_actors
  has_many :actors, through: :movie_actors
  has_many :movie_directors
  has_many :directors, through: :movie_directors
  has_many :movie_countries
  has_many :countries, through: :movie_countries
  has_many :movie_filming_locations
  has_many :filming_locations, through: :movie_filming_locations
  has_many :reviews
  has_many :users, through: :reviews
end

app/models/movie_actor.rb
# == Schema Information
#
# Table name: movie_actors
#
#  id         :bigint           not null, primary key
#  movie_id   :bigint           not null
#  actor_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_country.rb
# == Schema Information
#
# Table name: movie_countries
#
#  id         :bigint           not null, primary key
#  movie_id   :bigint           not null
#  country_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MovieCountry < ApplicationRecord
  belongs_to :movie
  belongs_to :country
end

app/models/movie_director.rb
# == Schema Information
#
# Table name: movie_directors
#
#  id          :bigint           not null, primary key
#  movie_id    :bigint           not null
#  director_id :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class MovieDirector < ApplicationRecord
  belongs_to :movie
  belongs_to :director
end

app/models/movie_filming_location.rb
# == Schema Information
#
# Table name: movie_filming_locations
#
#  id                  :bigint           not null, primary key
#  movie_id            :bigint           not null
#  filming_location_id :bigint           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class MovieFilmingLocation < ApplicationRecord
  belongs_to :movie
  belongs_to :filming_location
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  comment    :text
#  rating     :integer
#  movie_id   :bigint           not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  after_create :update_movie_rating

  private 

  def update_movie_rating
    new_rating = self.movie.reviews.map{|rev| rev.rating}.sum
    self.movie.update_column(:rating, new_rating.to_f/5)
  end 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_many :reviews
  has_many :movies, through: :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all.order("movies.rating desc")
  end

  def search
    actors = Actor.search(params[:actor])
    @movies = actors.map{|act| act.movies}.flatten.sort_by{ |obj| obj.rating }.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendAssessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/movies/index.html.erb
<%= render "shared/header" %>

<div class="container mx-auto py-4">
  <div class="grid gap-4 grid-cols-4 grid-rows-2">
    <% @movies.each do |movie|%>
      <div class="flex justify-center">
        <div class="rounded-lg shadow-lg bg-white max-w-sm">
          <a href="#!">
            <img class="rounded-t-lg" src="https://mdbootstrap.com/img/new/standard/nature/184.jpg" alt=""/>
          </a>
          <div class="p-6">
            <h5 class="text-gray-900 text-xl font-medium mb-2"><%= movie.title %></h5>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Description:</span> <%= movie.description %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Actors:</span> <%= movie.actors.map{|a| a.name}.join(', ') %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Directors:</span> <%= movie.directors.map{|a| a.name}.join(', ') %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Rating:</span> <%= movie.rating %>
            </p>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/movies/search.html.erb
<%= render "shared/header" %>

<div class="container mx-auto py-4">
  <div class="grid gap-4 grid-cols-4 grid-rows-2">
    <% @movies.each do |movie|%>
      <div class="flex justify-center">
        <div class="rounded-lg shadow-lg bg-white max-w-sm">
          <a href="#!">
            <img class="rounded-t-lg" src="https://mdbootstrap.com/img/new/standard/nature/184.jpg" alt=""/>
          </a>
          <div class="p-6">
            <h5 class="text-gray-900 text-xl font-medium mb-2"><%= movie.title %></h5>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Description:</span> <%= movie.description %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Actors:</span> <%= movie.actors.map{|a| a.name}.join(', ') %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Directors:</span> <%= movie.directors.map{|a| a.name}.join(', ') %>
            </p>
            <p class="text-gray-700 text-base mb-4">
              <span class="font-bold">Rating:</span> <%= movie.rating %>
            </p>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="font-sans flex flex-col bg-slate-200 text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 bg-white shadow sm:items-baseline w-full">
  <div class="grid gap-4 grid-cols-4 grid-rows-1">
    <div>
      <div class="mb-2 sm:mb-0">
        <a href="/home" class="text-2xl no-underline text-grey-darkest hover:text-blue-dark">Movies</a>
      </div>
    </div>
    <div></div>
    <div></div>
    <div class="flex justify-center">
      <%= form_with url: search_movies_path, method: :get do |f| %>
        <div class="input-group relative flex flex-wrap items-stretch w-full">
          <%= f.text_field :actor, class: "form-control relative flex-auto min-w-0 block px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none", placeholder: 'Search actor' %>
          <button class="btn inline-block px-6 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700  focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out flex items-center" type="submit" id="button-addon2">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="w-4" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
              <path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
            </svg>
          </button>
        </div>
      <%end%>
    </div>
  </div>
</nav>